---
- hosts: all
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    
    - name: Install python-setuptools
      apt:
        name: python-setuptools
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker
    # https://docs.docker.com/compose/cli-command/
    # - name: Install docker-compose
    #   get_url:
    #     url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
    #     dest: /usr/bin/docker-compose
    #     mode: 'u+x,g+x'
