---
- hosts: dev
  vars:
    project_path: /home/deploy/thaibot
  tasks:
    - name: Set some variable
      set_fact:
        current_path: "{{ project_path }}/current"
  
    - name: Run migration
      command: bash -lc "cd {{ current_path }} && /usr/bin/npm run migrate:deploy"
